name: Build Fabric 1.16.5 Mod

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build mod JAR
        run: ./gradlew clean remapJar --no-daemon

      - name: Show build/libs
        run: ls -l build/libs   # проверяем, что файл jar реально создан

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyFabricMod-JAR
          path: build/libs/*.jar
